// Mocks generated by Mockito 5.4.6 from annotations
// in to_do_app/test/todo/todo_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:to_do_app/features/auth/failures/failure.dart' as _i5;
import 'package:to_do_app/features/todo/entities/task_entity.dart' as _i6;
import 'package:to_do_app/features/todo/repositories/todo_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i2.TodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.TaskEntity>>> getTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getTodos, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.TaskEntity>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.TaskEntity>>>(
                    this,
                    Invocation.method(#getTodos, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.TaskEntity>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.TaskEntity>> createTodo({
    required String? title,
    String? description,
    String? category,
    int? priority,
    DateTime? dateTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTodo, [], {
              #title: title,
              #description: description,
              #category: category,
              #priority: priority,
              #dateTime: dateTime,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.TaskEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.TaskEntity>>(
                    this,
                    Invocation.method(#createTodo, [], {
                      #title: title,
                      #description: description,
                      #category: category,
                      #priority: priority,
                      #dateTime: dateTime,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.TaskEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.TaskEntity?>> updateTodo(
    int? id,
    _i6.TaskEntity? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodo, [id, data]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.TaskEntity?>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.TaskEntity?>>(
                    this,
                    Invocation.method(#updateTodo, [id, data]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.TaskEntity?>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteTodo(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodo, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#deleteTodo, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}
