// Mocks generated by Mockito 5.4.6 from annotations
// in to_do_app/test/todo/todo_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:to_do_app/features/todo/models/task_model/task_model.dart'
    as _i2;
import 'package:to_do_app/features/todo/repositories/todo_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaskModel_0 extends _i1.SmartFake implements _i2.TaskModel {
  _FakeTaskModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i3.TodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.TaskModel>> getTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getTodos, []),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<_i2.TaskModel> createTodo(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createTodo, [data]),
            returnValue: _i4.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(this, Invocation.method(#createTodo, [data])),
            ),
          )
          as _i4.Future<_i2.TaskModel>);

  @override
  _i4.Future<_i2.TaskModel?> updateTodo(int? id, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodo, [id, data]),
            returnValue: _i4.Future<_i2.TaskModel?>.value(),
          )
          as _i4.Future<_i2.TaskModel?>);

  @override
  _i4.Future<void> deleteTodo(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodo, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
