// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:to_do_app/features/todo/entities/task_entity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(TaskEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(TaskEntityAdapter());
  }
}
